#!/usr/bin/env bash

_module=$1;
if [ ! $_module ]; then
  read -p "Enter destination module's machine name: " _module;
fi;

_confd="./modules/custom/$_module/config/install";

cd ../web;

# Uninstall the module and clean up if it exists.
drupal module:uninstall $_module --yes > /dev/null;
rm -rf ./modules/custom/$_module;

# Generate the module and custom content types.
drupal chain --file="../.console/console.chain.yml";
echo "This module was generated by Drupal Console. It only contains install configurations." > ./modules/custom/$_module/README.txt;

# Tighten baseline node config.
sed "s/description: 'Generated by Drupal Console'/description: ''/g" -i $_confd/node.type.*.yml;
sed "s/preview_mode: 1/preview_mode: 0/g" -i $_confd/node.type.*.yml;
sed "s/display_submitted: true/display_submitted: false/g" -i $_confd/node.type.*.yml;

# Set tighter config to append to node.type.*.yml files.
read -r -d '' _append << EOM
langcode: en
status: true
dependencies:
    module:
        - menu_ui
third_party_settings:
    menu_ui:
        available_menus: { }
        parent: ''
EOM

# Truncate to last 8 lines, and append new config to node.type.*.yml files.
sed -n 11,18p -i $_confd/node.type.*.yml;
echo "$_append" | tee -a $_confd/node.type.*.yml > /dev/null;

# Set tighter config to append to core.entity_form_display.node.*.yml files.
read -r -d '' _append << EOM
content:
    title:
        type: string_textfield
        weight: 0
        settings:
            size: 60
            placeholder: ''
        third_party_settings: {  }
    body:
        type: text_textarea_with_summary
        weight: 1
        settings:
            rows: 9
            summary_rows: 2
            placeholder: ''
        third_party_settings: {  }
hidden:
    path: true
    uid: true
    created: true
    sticky: true
    promote: true
EOM

# Truncate to first 13 lines, and append new config to core.entity_form_display.node.*.yml files.
sed -n 1,13p -i $_confd/core.entity_form_display.node.*.yml;
echo "$_append" | tee -a $_confd/core.entity_form_display.node.*.yml > /dev/null;

# Remove generated teaser view modes.
rm -f $_confd/*.teaser.yml;

# Set tighter config to append to core.entity_view_display.node.*.default.yml files.
read -r -d '' _append << EOM
content:
  body:
    label: hidden
    type: text_default
    weight: 0
    settings: {  }
    third_party_settings: {  }
    region: content
hidden:
  links: true
EOM

# Truncate to first 13 lines, and append new config to core.entity_view_display.node.*.default.yml files.
sed -n 1,13p -i $_confd/core.entity_view_display.node.*.default.yml;
echo "$_append" | tee -a $_confd/core.entity_view_display.node.*.default.yml > /dev/null;

# Enable the module to install config.
drupal module:install $_module --yes;
